env: "dev" # local, dev, prod
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8080"
  timeout: 4s
  iddle_timeout: 60s

storage:
  max_open_conns: 300
  max_idle_conns: 150
  conn_max_life_time: 3s
